stationslist={
    "ALTN":{
    "name":"Arlington",
    "latitude":43.2966,
    "longitude":-89.3843,
    "location":"Arlington Agricultural Research Station",
    "region":"South Central",
    "state":"WI",
    },
    "BBCK":{
    "name":"Babcock",
    "latitude":44.2538,
    "longitude":-90.269,
    "location":"Amundson Cranberry Inc",
    "region":"Central",
    "state":"WI",
    },
    "BLCR":{
    "name":"Black Creek",
    "latitude":44.4815,
    "longitude":-88.4059,
    "location":"Fallen Timbers Environmental Center",
    "region":"East Central",
    "state":"WI",
    },
    "WCRS":{
    "name":"Black River Falls",
    "latitude":44.1852,
    "longitude":-90.7428,
    "location":"Black River Falls",
    "region":"West Central",
    "state":"WI",
    },
    "BRLN":{
    "name":"Brillion",
    "latitude":44.104,
    "longitude":-88.051,
    "location":"Dallmann East River Dairy LLC",
    "region":"East Central",
    "state":"WI",
    },
    "BSTL":{
    "name":"Bristol",
    "latitude":42.571,
    "longitude":-88.045,
    "location":"Kenosha County Center",
    "region":"Southeast",
    "state":"WI",
    },
    "CLLK":{
    "name":"Clear Lake",
    "latitude":45.2858,
    "longitude":-92.3213,
    "location":"Bull Brook Keep",
    "region":"Northwest",
    "state":"WI",
    },
    "COSP":{
    "name":"Cold Spring",
    "latitude":42.8987,
    "longitude":-88.7372,
    "location":"Cold Spring",
    "region":"South Central",
    "state":"WI",
    },
    "CTLR":{
    "name":"Cutler",
    "latitude":44.026,
    "longitude":-90.256,
    "location":"Cutler Cranberry",
    "region":"Central",
    "state":"WI",
    },
    "DEPR":{
    "name":"De Pere",
    "latitude":44.328,
    "longitude":-87.966,
    "location":"Calf Source LLC",
    "region":"East Central",
    "state":"WI",
    },
    "EGHA":{
    "name":"Egg Harbor",
    "latitude":45.0509,
    "longitude":-87.2598,
    "location":"Egg Harbor",
    "region":"East Central",
    "state":"WI",
    },
    "GFTN":{
    "name":"Grafton",
    "latitude":43.2981,
    "longitude":-87.9321,
    "location":"Grafton Little League",
    "region":"East Central",
    "state":"WI",
    },
    "GNWD":{
    "name":"Greenwood",
    "latitude":44.718,
    "longitude":-90.5966,
    "location":"Greenwood",
    "region":"North Central",
    "state":"WI",
    },
    "HNCK":{
    "name":"Hancock",
    "latitude":44.1188,
    "longitude":-89.5333,
    "location":"Not set",
    "region":"Central",
    "state":"WI",
    },
    "KSKM":{
    "name":"Kewaskum",
    "latitude":43.5351,
    "longitude":-88.2527,
    "location":"Blind Cow Dairy",
    "region":"East Central",
    "state":"WI",
    },
    "KWNE":{
    "name":"Kewaunee",
    "latitude":44.4018,
    "longitude":-87.6646,
    "location":"Kewaunee",
    "region":"East Central",
    "state":"WI",
    },
    "KNGT":{
    "name":"Knight",
    "latitude":46.289,
    "longitude":-90.436,
    "location":"Crawford Road Gravel Pit",
    "region":"North Central",
    "state":"WI",
    },
    "LAFG":{
    "name":"La Farge",
    "latitude":43.597,
    "longitude":-90.626,
    "location":"Kickapoo Valley Reserve Visitor Center",
    "region":"Western",
    "state":"WI",
    },
    "LNCT":{
    "name":"Lancaster",
    "latitude":42.83,
    "longitude":-90.7882,
    "location":"Not set",
    "region":"Southwest",
    "state":"WI",
    },
    "LXBG":{
    "name":"Luxemburg",
    "latitude":44.556,
    "longitude":-87.6543,
    "location":"Casco",
    "region":"East Central",
    "state":"WI",
    },
    "MNWT":{
    "name":"Manitowish Waters",
    "latitude":46.076,
    "longitude":-89.8383,
    "location":"Bartling&apos;s Manitowish Cranberry Company",
    "region":"North Central",
    "state":"WI",
    },
    "MRFD":{
    "name":"Marshfield",
    "latitude":44.7603,
    "longitude":-90.0978,
    "location":"Not set",
    "region":"North Central",
    "state":"WI",
    },
    "NASE":{
    "name":"Nasewaupee",
    "latitude":44.7894,
    "longitude":-87.4561,
    "location":"Nasewaupee",
    "region":"East Central",
    "state":"WI",
    },
    "NBLN":{
    "name":"New Berlin",
    "latitude":42.976,
    "longitude":-88.12,
    "location":"New Berlin City Hall",
    "region":"Southeast",
    "state":"WI",
    },
    "PARS":{
    "name":"PARS",
    "latitude":44.8802,
    "longitude":-87.3296,
    "location":"Sturgeon Bay",
    "region":"East Central",
    "state":"WI",
    },
    "FFEC":{
    "name":"Plover",
    "latitude":44.4461,
    "longitude":-89.5207,
    "location":"Food and Farm Exploration Center",
    "region":"Central",
    "state":"WI",
    },
    "GLCP":{
    "name":"Porter",
    "latitude":42.789,
    "longitude":-89.173,
    "location":"Gibbs Lake County Park",
    "region":"Southern",
    "state":"WI",
    },
    "DFRC":{
    "name":"Prairie du Sac",
    "latitude":43.3448,
    "longitude":-89.7117,
    "location":"Prairie du Sac",
    "region":"Southwest",
    "state":"WI",
    },
    "RNLD":{
    "name":"Rhinelander",
    "latitude":45.6546,
    "longitude":-89.2682,
    "location":"Not set",
    "region":"North Central",
    "state":"WI",
    },
    "RCHD":{
    "name":"Richland Center",
    "latitude":43.37,
    "longitude":-90.383,
    "location":"Richland County Highway Department",
    "region":"Southern",
    "state":"WI",
    },
    "RIPN":{
    "name":"Ripon",
    "latitude":43.9056,
    "longitude":-88.8467,
    "location":"Vines and Rushes Winery",
    "region":"East Central",
    "state":"WI",
    },
    "SIBA":{
    "name":"Sister Bay",
    "latitude":45.2191,
    "longitude":-87.0662,
    "location":"Sister Bay",
    "region":"East Central",
    "state":"WI",
    },
    "SODO":{
    "name":"Southern Door",
    "latitude":44.779,
    "longitude":-87.3556,
    "location":"Sturgeon Bay",
    "region":"East Central",
    "state":"WI",
    },
    "SPNR":{
    "name":"Spooner",
    "latitude":45.827,
    "longitude":-91.8614,
    "location":"Not set",
    "region":"Northwest",
    "state":"WI",
    },
    "OJNR":{
    "name":"Verona",
    "latitude":43.025,
    "longitude":-89.5367,
    "location":"Verona",
    "region":"South Central",
    "state":"WI",
    },
    "DUDA":{
    "name":"Walworth",
    "latitude":42.527,
    "longitude":-88.64,
    "location":"Blooming Duda&apos;s Flower Farm",
    "region":"Southeast",
    "state":"WI",
    },
    "WRNS":{
    "name":"Warrens",
    "latitude":44.1167,
    "longitude":-90.4121,
    "location":"Weatherby Cranberry Company",
    "region":"West Central",
    "state":"WI",
    },
    "WJPT":{
    "name":"West Jacksonport",
    "latitude":45.01,
    "longitude":-87.2335,
    "location":"West Jacksonport",
    "region":"East Central",
    "state":"WI",
    },
    "WNTEST1":{
    "name":"WiscNetTest",
    "latitude":43.2954,
    "longitude":-89.3582,
    "location":"Poultry Barn",
    "region":"South Central",
    "state":"WI",
    },
    "KEMP":{
    "name":"Woodruff",
    "latitude":45.841,
    "longitude":-89.6678,
    "location":"Woodruff",
    "region":"North Central",
    "state":"WI",
    },
    }